CREATE TABLE "USER" (
  "ID" SERIAL PRIMARY KEY,
  "username" VARCHAR(255) NOT NULL,
  "role" VARCHAR(255) NOT NULL
);

CREATE TABLE "DUTY" (
  "id" SERIAL PRIMARY KEY,
  "date" TIMESTAMP NOT NULL,
  "user_id1" int,
  "user_id2" int
);

CREATE TABLE "EVENT" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INT NOT NULL,
  "duty_id" INT NOT NULL,
  "event_type" VARCHAR(255) NOT NULL,
  "event_timestamp" TIMESTAMP NOT NULL
);

ALTER TABLE "EVENT" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("ID");

ALTER TABLE "EVENT" ADD FOREIGN KEY ("duty_id") REFERENCES "DUTY" ("id");

ALTER TABLE "DUTY" ADD CONSTRAINT "unique_user_id" UNIQUE ("user_id1");

ALTER TABLE "DUTY" ADD CONSTRAINT "unique_user_id2" UNIQUE ("user_id2");


ALTER TABLE "USER" ADD FOREIGN KEY ("ID") REFERENCES "DUTY" ("user_id1");

ALTER TABLE "USER" ADD FOREIGN KEY ("ID") REFERENCES "DUTY" ("user_id2");
